@startuml Register DataBase Schema v3
hide circle
skinparam linetype ortho

'========== MEMBER =========='
entity "Member" as M {
  *id : int <<PK>>
  last_name : varchar
  first_name : varchar
  present : bool
  arrival : date
  departure : date
  email : varchar
  personal_email : varchar
  phone : varchar
  discord : varchar
  notes : varchar
  srg : bool
  warning : int
  created_by : varchar
  created_at : date
  modified_by : varchar
  modified_at : date
  convs : bool
  portal : bool
  promotion_id : int <<FK>>
}

'========== STATUS =========='
entity "Status" as S {
  *id : int <<PK>>
  name : varchar
}

entity "Member_Status" as MS {
  *member_id : int <<FK>>
  *status_id : int <<FK>>
}

'========== PROMOTION =========='
entity "Promotion" as P {
  *id : int <<PK>>
  year : int
  level : varchar
  apprentice : bool
  school : int <<FK>>
  major : int <<FK>>
}

entity "School" as E {
  *id : int <<PK>>
  name : varchar
}

entity "Major" as MJ {
  *id : int <<PK>>
  name : varchar
  school_id : int <<FK>>
}


'========== CONTRIBUTION =========='
entity "Contribution" as C {
  *id : int <<PK>>
  member_id : int <<FK>>
  state : varchar
  payment_date : date
  amount : float
  payment_method : varchar
}

'========== INTERNAL REGULATION =========='
entity "IR" as IR {
  *id : int <<PK>>
  member_id : int <<FK>>
  state : varchar
  version : varchar
  signature_date : date
}

'========== ROLE =========='
entity "Role" as R {
  *id : int <<PK>>
  name : varchar
  description : varchar
  type : int <<FK>>
}

entity "RoleType" as RT {
  *id : int <<PK>>
  name : varchar
}

entity "Member_Role" as MR {
  *member_id : int <<FK>>
  *role_id : int <<FK>>
}

'========== TRAINING =========='
entity "Training" as T {
  *id : int <<PK>>
  name : varchar
  description : varchar
  type_id : int <<FK>>
}

entity "TrainingType" as TT {
  *id : int <<PK>>
  name : varchar
}

entity "Member_Training" as MT {
  *member_id : int <<FK>>
  *training_id : int <<FK>>
  participation_date : date
  status : varchar
}

'========== TRAINERS =========='

entity "Trainer" as MTR {
  *member_id : int <<FK>>
  *training_id : int <<FK>>
  assigned_date : date
}


'========== ASSOCIATIONS =========='
M ||--o{ MS : has
S ||--o{ MS : classified as
M }o--|| P : promotion
M ||--o{ C : contributes
M ||--o{ IR : signs
M ||--o{ MR : holds
R ||--o{ MR : defined by
M ||--o{ MT : attended
T ||--o{ MT : listed in
T }o--|| TT : categorized as
P }o--|| E : belongs to
P }o--|| MJ : specialized in
MJ }o--|| E : defined by
R }o--|| RT : categorized as
M ||--o{ MTR : trains
T ||--o{ MTR : has trainers

@enduml
